services:
  gtnh:
    image: itzg/minecraft-server:java25
    container_name: gtnh-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "29400:25565"
      - "2324:2324"
    environment:
      EULA: "TRUE"
      TYPE: "GTNH"
      GTNH_PACK_VERSION: "2.8.4"

      # Nach dem ersten Start auf true setzen – verhindert unnötige Update-Checks
      SKIP_GTNH_UPDATE_CHECK: "false"

      # Alte Config-Backups beim Start löschen (optional)
      GTNH_DELETE_BACKUPS: "false"

      # Bestätigt automatisch die FML-Frage beim Update (mod list changed for existing world)
      JVM_OPTS: "-Dfml.queryResult=confirm"

      # Memory – 6GB minimum, +0.5–1GB pro Spieler je nach Spielfortschritt
      MEMORY: "16G"

      # Server-Einstellungen
      OPS: ""    # Kommagetrennte Spielernamen für OPs

    volumes:
      - ./data:/data

    mem_limit: 18g
    mem_reservation: 16g

    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
